#!/bin/sh

PATH="$HOME/.config/via:$PATH"

command='files'
prompt='via'

while getopts 'mA' opt; do
    case "${opt}" in
        m) command='songs'
            prompt='Select song:';;
        A) via-feed 'albums'
            exit 0;;
    esac
done

via-feed $command | via-menu "$prompt" | via-open
