#!/bin/bash

cat "$HOME/.config/via/shortcuts"
cat "$HOME/.config/via/websites"
find "$HOME" -mindepth 1 \( -name ".*" -o -path "$HOME/bin" -o -path "$HOME/Desktop" -o -path "$HOME/Music" -o -path "$HOME/MEGA" -o -path "$HOME/R" -o -path "$HOME/snap" \) -prune -o -print | sort
